unsigned char byref_FF[] = {2, BYREF_FORCE,BYREF_FORCE};
unsigned char byref_F[] = {1, BYREF_FORCE};
unsigned char byref_FFF[] = {3, BYREF_FORCE,BYREF_FORCE,BYREF_FORCE};
unsigned char byref_AAF[] = {3, BYREF_ALLOW,BYREF_ALLOW,BYREF_FORCE};
unsigned char byref_AAFFFFFF[] = {8, BYREF_ALLOW,BYREF_ALLOW,BYREF_FORCE,BYREF_FORCE,BYREF_FORCE,BYREF_FORCE,BYREF_FORCE,BYREF_FORCE};
unsigned char byref_AAFF[] = {4, BYREF_ALLOW,BYREF_ALLOW,BYREF_FORCE,BYREF_FORCE};
