#!/bin/sh 
#
# $Id$

dir=$1; shift

if [[ "$dir" == *ext ]]; then
    echo "sinclude([$dir/gtk+/config.m4])"
fi

for stubfile in $dir/*/config.m4; do
    if [[ "$stubfile" != *skeleton* && "$stubfile" != *gtk\+* ]]; then
        echo "sinclude([$stubfile])"
    fi
done
