#!/bin/sh 
#
# $Id$

dir=$1; shift

echo "sinclude([$dir/gtk+/config.m4])"
for stubfile in $dir/*/config.m4; do
    if ! expr $stubfile : '.*/gtk\+/.*' >/dev/null; then
        echo "sinclude([$stubfile])"
    fi
done
