<?php
// Call GtkBoxTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "GtkBoxTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

// You may remove the following line when all tests have been implemented.
require_once "PHPUnit/Framework/IncompleteTestError.php";



/**
 * Test class for GtkBox.
 * Generated by PHPUnit_Util_Skeleton on 2006-03-07 at 13:26:40.
 */
class GtkBoxTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("GtkBoxTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testGet_homogeneous().
     */
    public function testGet_homogeneous() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testGet_spacing().
     */
    public function testGet_spacing() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testPack_end().
     */
    public function testPack_end() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testPack_end_defaults().
     */
    public function testPack_end_defaults() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testPack_start().
     */
    public function testPack_start() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testPack_start_defaults().
     */
    public function testPack_start_defaults() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     *
    */
    public function testQuery_child_packing() {
        $vb = new GtkVBox();
        $vb->pack_start($c1 = new GtkLabel('Page 1'), true, true, 0);
        list($expand, $fill, $padding, $pack_type) = $vb->query_child_packing($c1);
        $this->assertTrue($expand);
        $this->assertTrue($fill);
        $this->assertEquals(0, $padding);
        $this->assertEquals(Gtk::PACK_START, $pack_type);

        $vb->pack_start($c2 = new GtkLabel('Page 2'), true, false, 10);
        list($expand, $fill, $padding, $pack_type) = $vb->query_child_packing($c2);
        $this->assertTrue($expand);
        $this->assertFalse($fill);
        $this->assertEquals(10, $padding);
        $this->assertEquals(Gtk::PACK_START, $pack_type);

        $vb->pack_end($c3 = new GtkLabel('Page 3'), false, false, 1000);
        list($expand, $fill, $padding, $pack_type) = $vb->query_child_packing($c3);
        $this->assertFalse($expand);
        $this->assertFalse($fill);
        $this->assertEquals(1000, $padding);
        $this->assertEquals(Gtk::PACK_END, $pack_type);
    }

    /**
     * @todo Implement testReorder_child().
     */
    public function testReorder_child() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSet_child_packing().
     */
    public function testSet_child_packing() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSet_homogeneous().
     */
    public function testSet_homogeneous() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }

    /**
     * @todo Implement testSet_spacing().
     */
    public function testSet_spacing() {
        // Remove the following line when you implement this test.
        throw new PHPUnit_Framework_IncompleteTestError;
    }
}

// Call GtkBoxTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "GtkBoxTest::main") {
    GtkBoxTest::main();
}
?>
